
###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine As development

# Create app directory
WORKDIR /app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm install

RUN npm install -g nodemon

RUN npm install -g @nestjs/cli

# Bundle app source
COPY . .

RUN apk add --no-cache bash

EXPOSE 5500

# RUN npm run build

